# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-30 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_bord',
            name='image_url',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
